### ISSUE TITLE
Ningun contrato deberia tener una funcion para retirar el ETH

### ISSUE THREAD

**Issue by Goro2030** [proyectowea/RandomBets#2]
Como usuario, no entraría a ningun concurso donde el owner pueda retirar el ETH con una simple llamada a una funcion.

Recomiendo remover dicha funcion, y quizas si piensan que puede haber algun hecho catastrófico , poner una funcion PAUSE. Esto pueden hacerlo facilmente heredando el IsPausable de OpenZeppelin

**Comment by cryptowea** [comment]
gracias por sus observaciones.
